apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-argocd
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: go-argocd
  template:
    metadata:
      labels:
        app: go-argocd
    spec:
      containers:
      - image: eduardomarcon/go-argocd:1.0.4
        name: go-argocd
        ports:
        - containerPort: 8080
